baseURL = 'https://blindcoders.com'
languageCode = 'en-us'
title = 'Blind Coders'

theme = "blindcoders"

[module]
[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"
